image: gcc

variables:
  file_changes: "**/{*.hpp,*.cpp,CMakeLists.txt,.gitlab-ci.yml}"

stages:
  - build
  - package

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake ninja-build rpm

build:
  stage: build
  script:
    - cmake -S . -B build -G Ninja
    - cmake --build build --config Release
  rules:
    - changes:
        - $file_changes

package:
  stage: package
  script:
    - cmake -S . -B build -G Ninja
    - cmake --build build --config Release
    - cd build && cpack --verbose
  dependencies:
    - build
  rules:
    - changes:
        - $file_changes
  artifacts:
    paths:
      - build/*.deb
      - build/*.rpm
